### ISSUE TITLE
Link to "Client operator" broke

### ISSUE THREAD

**Issue by rahul0eth** [chainrule-labs/shaave-docs-v2#1]
Link to definition of "Client Operator" should point to glossary page, but is broken on the following pages:
1. https://docs.pesto.finance/faq/fees
2. https://docs.pesto.finance/technical-docs/contracts/position
3. https://docs.pesto.finance/technical-docs/contracts/fee-collector

Replace [Client operators](/references/glossary/mdx) with [Client operators](/references/glossary.mdx)

**Comment by 0xernesto** [comment]
Thanks for spotting this and opening an issue.
Fixed and pushed to main: [9fbaa09d6f6fc22ccf3c07ba68e08bda4d5df2ee](https://github.com/chainrule-labs/pesto-docs/commit/9fbaa09d6f6fc22ccf3c07ba68e08bda4d5df2ee)

**Comment by 0xernesto** [comment]
Thanks for spotting this and opening an issue.
Fixed and pushed to main: [9fbaa09d6f6fc22ccf3c07ba68e08bda4d5df2ee](https://github.com/chainrule-labs/pesto-docs/commit/9fbaa09d6f6fc22ccf3c07ba68e08bda4d5df2ee)
